spring.application.name=bike
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-millis=${JWT_EXPIRATION_MILLIS}

seoul-bike.api-key=${SEOUL_BIKE_API_KEY}
kma.weather.api-key=${KMA_WEATHER_API_KEY}
seoul-bike.realtime-cache.ttl-seconds=15
seoul-bike.realtime-cache.null-ttl-seconds=5
seoul-bike.realtime-cache.lock-ttl-seconds=3
seoul-bike.realtime-cache.wait-timeout-millis=2500
seoul-bike.realtime-cache.poll-interval-millis=50

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
